### ISSUE TITLE
asteroid-alarmclock not Show/Missing Correct words

### ISSUE THREAD

**Issue by ghost** [AsteroidOS/asteroid-alarmclock#5]
?xml version="1.0" encoding="utf-8"?>
!DOCTYPE TS>
TS version="2.1" language="es">
context>
 name>AlarmTimePickerDialog</name>
 message>
location filename="../AlarmTimePickerDialog.qml" line="37"/>
source>New Alarm</source>
translation>Nueva Alarma</translation >   >>  " Show in capital letter like this NUEVA ALARMA  in *es.ts "
- Also in this app there are words in Spanish example "mon. tus. wed. thu. fri. sat. sun. That I did not translate, but also these strings of words are not found in *es.ts I need these words at freedom to modify it.

**Comment by FlorentRevest** [comment]
Both of the reported behaviors are expected:
- It has been decided by designers that titles should be left uppercase. translators shouldn't have the right to change the designers decisions. https://github.com/AsteroidOS/asteroid-alarmclock/blob/master/alarmclock/AlarmTimePickerDialog.qml#L37
- Day names are standard and are kept maintained by the Qt project. https://github.com/AsteroidOS/asteroid-alarmclock/blob/master/alarmclock/DayButton.qml#L35 They are not exposed to translators on purpose.

"It's not a bug, it's a feature"
